spring:
  datasource:
    url: jdbc:h2:mem://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

# logger 를 통해 하이버네이 실행 SQL 을 남긴다
logging:
  level:
    org.hibernate.SQL: debug